### ISSUE TITLE
show message/warning when angle deviations are present

### ISSUE THREAD

**Issue by ricardoavelino** [BlockResearchGroup/compas_ags#56]
Hi, this is a feature request for somehow showing the user that angle deviations are present in the design. This may be useful specially for not so experienced users. Here is an example, I modified (purposely wrong) the Force Diagram while keeping the bottom chord constrained. The 2 diagrams are of course not reciprocal since edge 18 can not move its inclination:

<img width="1228" alt="image" src="https://user-images.githubusercontent.com/36137188/89654302-ce8cfc80-d89e-11ea-9c75-33034f3f767d.png">

I was imagining some mechanism like RhinoVAULT that shows the diagram in red when it is not in horizontal equilibrium. However, since we do quite a lot of red/blue, painting the diagram in red may be bad... So up to discussion here about the best way to do that...

Thanks

**Comment by juney-lee** [comment]
@brgcode after moving some vertices in the force diagram, the form diagram updates and redraws, but something that is clearly not parllelised/equilibrated... in cases like this, do we display the form diagram in red (as in RV2, when there is no vertical equilibrium)? But then I am not sure what the simple solution in AGS would be, since you can't really recompute or revert...

**Comment by ricardoavelino** [comment]
See PR #63

**Comment by ricardoavelino** [comment]
done
