### ISSUE TITLE
edge labels

### ISSUE THREAD

**Issue by duchaoyu** [BlockResearchGroup/compas_ags#80]
After we inplement inspectors, information table, the current edge labels would be hided by default displaysetting. 
For FormDiagram, internal strcuture would be drawn as pipes, without edgelabels. External forces would be drawn as arrowed lines and they would have edgelabel showing force magnitude.

**Comment by ricardoavelino** [comment]
The current initial visualisation is the force magnitudes, instead of the edge labels:

<img width="585" alt="image" src="https://user-images.githubusercontent.com/36137188/93072217-642b6100-f681-11ea-81a5-3b07e96a877b.png">

Plus, these forces don't update correctly after assigning forces to independents:

<img width="744" alt="image" src="https://user-images.githubusercontent.com/36137188/93073001-85d91800-f682-11ea-82e7-a6ae190a46eb.png">

**Comment by ricardoavelino** [comment]
done
